### ISSUE TITLE
Sugestão de motor para gerar postagens

### ISSUE THREAD

**Issue by mstuttgart** [odoo-brazil/odoo-brazil.github.io#1]
@mileo tem em mente algum motor para gerar o site?

Caso não tenha, eu indicaria o [Pelican](http://pythonclub.com.br/criando-sites-estaticos-com-pelican.html). Ele é em python e as postagens podem ser escritas usando *markdown*. Também permite  automatizar a publicação das postagens usando o TravisCI. Caso queira usar ele só me falar, que eu posso contribuir. Uso ele em meu blog: https://github.com/mstuttgart/mstuttgart.github.io

Também existe o mkdocs, usado para criar documentação. Ele também permite escrever as paginas usando *markdown*. Usei ele para criar o site do meu projeto: https://github.com/pynocchio/pynocchio.github.io/tree/mkdocs

**Comment by mileo** [comment]
Eu tb prefiro o Pelican, por ser python, mas o Renato me disse que já iniciou o template em Jerkill.

Eu só criei o Hello Word para verificar se não ia ferrar a url do material q estou fazendo https://odoo-brazil.github.io/odoo-developer-tutorial/

cc: @renatonlima
